### ISSUE TITLE
Is there an original source code for the stuff?

### ISSUE THREAD

**Issue by sualex** [JavoByte/redux-saga-socket-cluster#1]
@JavoByte Hi, Javier. Have you still got the non-transpiled source for the package? Could you kindly provide it since it would help me a lot not to reinvent the wheel :) .

Thanks in advance.

**Comment by JavoByte** [comment]
Hi, check it out in the `develop` branch.

**Comment by sualex** [comment]
Oh my ) . It was late at night ... Thanks.
